name: CI

on:
  push:
    branches:
      - dependency_controller
  pull_request:
    branches:
      - dependency_controller

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python you need
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt